# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f65d8bcd9d044ff31f2223200ac9e950c150b29605fe371d010fc7a3b4ad4eb89d2fd1fac8e1ae5546e013b27b317e0b30ae5f93627d5568fb80366017c9a16

test:
  secret_key_base: afedcd56105094adf381ba297927b5e405d0221b2c2e92e65d23c702b74403d85efff58bb417f1cf11814e2aff41ad6526732c911e61e32f81efeae6cefbc073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
